// src/lib/profilesData.js (or wherever you store this)

export const profiles = [
  // --- Profiles 1-10 (from previous example) ---
  {
    id: "1",
    name: "Aarav Sharma",
    title: "Senior Developer",
    location: "Bengaluru, Karnataka",
    email: "aarav@example.com",
    phone: "(+91) 98765-43210",
    description: "Experienced developer passionate about building scalable web applications. Specializes in React, Python, and cloud technologies.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/1.jpg`,
    interests: ["Coding", "Cricket", "Travel", "Open Source"],
    experience: [
      { title: "Senior Developer", company: "TechMahindra", period: "2020 - Present" },
      { title: "Developer", company: "Infosys", period: "2017 - 2020" },
    ],
    education: [
      { degree: "Computer Science", institution: "IIT Delhi", period: "2013 - 2017" },
    ],
  },
  {
    id: "2",
    name: "Priya Patel",
    title: "UX Designer",
    location: "Mumbai, Maharashtra",
    email: "priya@example.com",
    phone: "(+91) 87654-32109",
    description: "Creative designer with a focus on user-friendly interfaces. Skilled in UI/UX design, prototyping, and user research.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/2.jpg`,
    interests: ["Design Thinking", "Bollywood", "Dance", "Art"],
    experience: [
      { title: "Senior UX Designer", company: "DesignWorks India", period: "2019 - Present" },
      { title: "UX Designer", company: "Creative Labs", period: "2016 - 2019" },
    ],
    education: [
      { degree: "Graphic Design", institution: "NID Ahmedabad", period: "2012 - 2016" },
    ],
  },
  {
    id: "3",
    name: "Rohan Gupta",
    title: "Product Manager",
    location: "Gurugram, Haryana",
    email: "rohan@example.com",
    phone: "(+91) 76543-21098",
    description: "Strategic product manager with experience in fintech products. Expert in Agile methodologies and stakeholder collaboration.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/3.jpg`,
    interests: ["Product Strategy", "Chess", "Food Blogging", "Tech Trends"],
    experience: [
      { title: "Product Manager", company: "Paytm", period: "2018 - Present" },
      { title: "Associate Product Manager", company: "Zomato", period: "2016 - 2018" },
    ],
    education: [
      { degree: "MBA", institution: "IIM Bangalore", period: "2014 - 2016" },
    ],
  },
  {
    id: "4",
    name: "Neha Reddy",
    title: "Data Scientist",
    location: "Hyderabad, Telangana",
    email: "neha@example.com",
    phone: "(+91) 65432-10987",
    description: "Data scientist with a knack for machine learning and predictive analytics. Passionate about data-driven decision-making.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/4.jpg`,
    interests: ["Machine Learning", "Yoga", "Cooking", "Data Visualization"],
    experience: [
      { title: "Senior Data Scientist", company: "TCS", period: "2019 - Present" },
      { title: "Data Analyst", company: "Wipro", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Statistics", institution: "University of Hyderabad", period: "2013 - 2017" },
    ],
  },
  {
    id: "5",
    name: "Vikram Singh",
    title: "DevOps Engineer",
    location: "Pune, Maharashtra",
    email: "vikram@example.com",
    phone: "(+91) 91234-56780",
    description: "Experienced DevOps engineer focusing on CI/CD pipelines and cloud infrastructure.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/5.jpg`,
    interests: ["Automation", "Cloud Computing", "Hiking", "Gaming"],
    experience: [
      { title: "DevOps Engineer", company: "Infosys", period: "2019 - Present" },
      { title: "System Administrator", company: "HCL", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Information Technology", institution: "Pune University", period: "2013 - 2017" },
    ],
  },
  {
    id: "6",
    name: "Ananya Iyer",
    title: "Marketing Specialist",
    location: "Chennai, Tamil Nadu",
    email: "ananya@example.com",
    phone: "(+91) 92345-67891",
    description: "Digital marketing expert skilled in SEO, SEM, and social media campaigns.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/6.jpg`,
    interests: ["Digital Marketing", "Reading", "Classical Music", "Content Creation"],
    experience: [
      { title: "Marketing Specialist", company: "Flipkart", period: "2020 - Present" },
      { title: "Marketing Intern", company: "Freshworks", period: "2019 - 2020" },
    ],
    education: [
      { degree: "Marketing", institution: "Madras University", period: "2015 - 2019" },
    ],
  },
  {
    id: "7",
    name: "Kunal Mehra",
    title: "Software Engineer",
    location: "Bengaluru, Karnataka",
    email: "kunal@example.com",
    phone: "(+91) 93456-78902",
    description: "Software engineer building robust backend systems with Java and Spring.",
    status: "Inactive",
    avatar: `https://randomuser.me/api/portraits/men/7.jpg`,
    interests: ["Backend Development", "Photography", "Cycling", "Tech Meetups"],
    experience: [
      { title: "Software Engineer", company: "Wipro", period: "2018 - Present" },
      { title: "Junior Engineer", company: "TCS", period: "2016 - 2018" },
    ],
    education: [
      { degree: "Computer Engineering", institution: "VIT Vellore", period: "2012 - 2016" },
    ],
  },
  {
    id: "8",
    name: "Sneha Nair",
    title: "QA Analyst",
    location: "Mumbai, Maharashtra",
    email: "sneha@example.com",
    phone: "(+91) 94567-89013",
    description: "Detail-oriented QA analyst ensuring software quality through rigorous testing.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/8.jpg`,
    interests: ["Software Testing", "Baking", "Movies", "Automation Testing"],
    experience: [
      { title: "QA Analyst", company: "LTI", period: "2019 - Present" },
      { title: "Test Engineer", company: "Capgemini", period: "2017 - 2019" },
    ],
    education: [
      { degree: "B.Sc. IT", institution: "Mumbai University", period: "2013 - 2017" },
    ],
  },
  {
    id: "9",
    name: "Arjun Rao",
    title: "Data Analyst",
    location: "Hyderabad, Telangana",
    email: "arjun@example.com",
    phone: "(+91) 95678-90124",
    description: "Data analyst transforming raw data into actionable business insights.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/9.jpg`,
    interests: ["Data Analysis", "SQL", "Tableau", "Football"],
    experience: [
      { title: "Data Analyst", company: "Deloitte", period: "2020 - Present" },
      { title: "Junior Analyst", company: "Accenture", period: "2018 - 2020" },
    ],
    education: [
      { degree: "Economics", institution: "Osmania University", period: "2014 - 2018" },
    ],
  },
  {
    id: "10",
    name: "Pooja Desai",
    title: "Frontend Developer",
    location: "Gurugram, Haryana",
    email: "pooja@example.com",
    phone: "(+91) 96789-01235",
    description: "Frontend developer creating engaging user interfaces with React and modern JavaScript.",
    status: "Inactive",
    avatar: `https://randomuser.me/api/portraits/women/10.jpg`,
    interests: ["Frontend Development", "UI Design", "Painting", "Yoga"],
    experience: [
      { title: "Frontend Developer", company: "Zomato", period: "2019 - Present" },
      { title: "Web Developer", company: "MakeMyTrip", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Computer Applications", institution: "Delhi University", period: "2013 - 2017" },
    ],
  },

  // --- Profiles 11-50 ---
  {
    id: "11",
    name: "Siddharth Jain",
    title: "Cloud Architect",
    location: "Delhi",
    email: "siddharth@example.com",
    phone: "(+91) 97890-12346",
    description: "Designing and implementing scalable cloud solutions on AWS and Azure.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/11.jpg`,
    interests: ["Cloud Architecture", "Microservices", "Reading", "Trekking"],
    experience: [
      { title: "Cloud Architect", company: "Accenture", period: "2021 - Present" },
      { title: "Senior Cloud Engineer", company: "HCL", period: "2018 - 2021" },
    ],
    education: [
      { degree: "M.Tech Cloud Computing", institution: "BITS Pilani", period: "2016 - 2018" },
    ],
  },
  {
    id: "12",
    name: "Meera Bose",
    title: "Content Writer",
    location: "Kolkata, West Bengal",
    email: "meera@example.com",
    phone: "(+91) 98901-23457",
    description: "Crafting compelling content for blogs, websites, and marketing materials.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/12.jpg`,
    interests: ["Content Strategy", "Creative Writing", "History", "Gardening"],
    experience: [
      { title: "Content Lead", company: "Tech Startup", period: "2020 - Present" },
      { title: "Content Writer", company: "Digital Agency", period: "2018 - 2020" },
    ],
    education: [
      { degree: "English Literature", institution: "Jadavpur University", period: "2014 - 2018" },
    ],
  },
  {
    id: "13",
    name: "Rahul Kapoor",
    title: "Mobile Developer (Android)",
    location: "Pune, Maharashtra",
    email: "rahul.k@example.com",
    phone: "(+91) 99012-34568",
    description: "Building native Android applications with Kotlin and Java.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/13.jpg`,
    interests: ["Android Development", "Kotlin", "Mobile UI/UX", "Motorbiking"],
    experience: [
      { title: "Android Developer", company: "Persistent Systems", period: "2019 - Present" },
      { title: "Junior Developer", company: "Mobile Solutions Ltd", period: "2017 - 2019" },
    ],
    education: [
      { degree: "B.E. Computer Science", institution: "COEP Pune", period: "2013 - 2017" },
    ],
  },
  {
    id: "14",
    name: "Divya Menon",
    title: "HR Manager",
    location: "Chennai, Tamil Nadu",
    email: "divya@example.com",
    phone: "(+91) 90123-45679",
    description: "Experienced HR professional managing recruitment, employee relations, and performance.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/14.jpg`,
    interests: ["Talent Acquisition", "Employee Engagement", "Travel", "Cooking"],
    experience: [
      { title: "HR Manager", company: "Infosys", period: "2018 - Present" },
      { title: "HR Executive", company: "TCS", period: "2015 - 2018" },
    ],
    education: [
      { degree: "MBA HR", institution: "Symbiosis Pune", period: "2013 - 2015" },
    ],
  },
  {
    id: "15",
    name: "Aditya Verma",
    title: "Business Analyst",
    location: "Bengaluru, Karnataka",
    email: "aditya@example.com",
    phone: "(+91) 91234-56780",
    description: "Bridging the gap between business needs and technical solutions.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/15.jpg`,
    interests: ["Requirements Gathering", "Process Improvement", "Finance", "Badminton"],
    experience: [
      { title: "Senior Business Analyst", company: "Wipro", period: "2020 - Present" },
      { title: "Business Analyst", company: "Capgemini", period: "2017 - 2020" },
    ],
    education: [
      { degree: "B.Com", institution: "Christ University", period: "2013 - 2017" },
    ],
  },
  {
    id: "16",
    name: "Ishita Sharma",
    title: "Graphic Designer",
    location: "Delhi",
    email: "ishita@example.com",
    phone: "(+91) 92345-67891",
    description: "Creating visually appealing designs for branding, marketing, and digital media.",
    status: "Inactive",
    avatar: `https://randomuser.me/api/portraits/women/16.jpg`,
    interests: ["Branding", "Illustration", "Typography", "Art Galleries"],
    experience: [
      { title: "Graphic Designer", company: "Ogilvy", period: "2019 - Present" },
      { title: "Junior Designer", company: "Design Studio", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Fine Arts", institution: "Delhi College of Art", period: "2013 - 2017" },
    ],
  },
  {
    id: "17",
    name: "Mohit Agarwal",
    title: "Full Stack Developer",
    location: "Hyderabad, Telangana",
    email: "mohit@example.com",
    phone: "(+91) 93456-78902",
    description: "Versatile developer working on both frontend (React) and backend (Node.js).",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/17.jpg`,
    interests: ["JavaScript", "Node.js", "React", "Music Production"],
    experience: [
      { title: "Full Stack Developer", company: "Microsoft", period: "2018 - Present" },
      { title: "Software Engineer", company: "Startup Hub", period: "2016 - 2018" },
    ],
    education: [
      { degree: "B.Tech CSE", institution: "IIIT Hyderabad", period: "2012 - 2016" },
    ],
  },
  {
    id: "18",
    name: "Riya Singh",
    title: "Project Manager",
    location: "Mumbai, Maharashtra",
    email: "riya@example.com",
    phone: "(+91) 94567-89013",
    description: "Managing software development projects using Agile and Scrum methodologies.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/18.jpg`,
    interests: ["Agile", "Scrum", "Project Planning", "Yoga"],
    experience: [
      { title: "Project Manager", company: "TechMahindra", period: "2019 - Present" },
      { title: "Scrum Master", company: "LTI", period: "2017 - 2019" },
    ],
    education: [
      { degree: "PMP Certification", institution: "PMI", period: "2019" },
      { degree: "B.E. IT", institution: "Mumbai University", period: "2012 - 2016" },
    ],
  },
  {
    id: "19",
    name: "Sameer Khan",
    title: "Network Engineer",
    location: "Gurugram, Haryana",
    email: "sameer@example.com",
    phone: "(+91) 95678-90124",
    description: "Designing, implementing, and maintaining network infrastructure.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/19.jpg`,
    interests: ["Network Security", "Cisco", "Cloud Networking", "Cricket"],
    experience: [
      { title: "Network Engineer", company: "Airtel", period: "2017 - Present" },
      { title: "Network Admin", company: "Local ISP", period: "2015 - 2017" },
    ],
    education: [
      { degree: "CCNA/CCNP", institution: "Cisco", period: "Ongoing" },
      { degree: "B.Sc Electronics", institution: "Kurukshetra University", period: "2011 - 2015" },
    ],
  },
  {
    id: "20",
    name: "Tanvi Shah",
    title: "UI Designer",
    location: "Pune, Maharashtra",
    email: "tanvi@example.com",
    phone: "(+91) 96789-01235",
    description: "Designing intuitive and visually appealing user interfaces for web and mobile.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/20.jpg`,
    interests: ["UI Design", "Figma", "Prototyping", "Sketching"],
    experience: [
      { title: "Senior UI Designer", company: "Globant", period: "2020 - Present" },
      { title: "UI Designer", company: "Design Firm", period: "2018 - 2020" },
    ],
    education: [
      { degree: "Interaction Design", institution: "MIT Institute of Design", period: "2014 - 2018" },
    ],
  },
  {
    id: "21",
    name: "Deepak Kumar",
    title: "Database Administrator",
    location: "Chennai, Tamil Nadu",
    email: "deepak@example.com",
    phone: "(+91) 97890-12346",
    description: "Managing and maintaining database systems (SQL Server, Oracle).",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/21.jpg`,
    interests: ["Database Management", "SQL Tuning", "Backup & Recovery", "Chess"],
    experience: [
      { title: "DBA", company: "Cognizant", period: "2016 - Present" },
      { title: "Junior DBA", company: "HCL", period: "2014 - 2016" },
    ],
    education: [
      { degree: "MCA", institution: "Anna University", period: "2011 - 2014" },
    ],
  },
  {
    id: "22",
    name: "Natasha Singh",
    title: "SEO Specialist",
    location: "Delhi",
    email: "natasha@example.com",
    phone: "(+91) 98901-23457",
    description: "Improving website visibility on search engines through on-page and off-page SEO.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/22.jpg`,
    interests: ["SEO", "Keyword Research", "Link Building", "Analytics"],
    experience: [
      { title: "SEO Lead", company: "Digital Marketing Agency", period: "2019 - Present" },
      { title: "SEO Executive", company: "E-commerce Startup", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Mass Communication", institution: "IP University", period: "2013 - 2017" },
    ],
  },
  {
    id: "23",
    name: "Vivek Anand",
    title: "Machine Learning Engineer",
    location: "Bengaluru, Karnataka",
    email: "vivek@example.com",
    phone: "(+91) 99012-34568",
    description: "Developing and deploying machine learning models.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/23.jpg`,
    interests: ["Machine Learning", "Python", "TensorFlow", "AI Ethics"],
    experience: [
      { title: "ML Engineer", company: "Amazon", period: "2020 - Present" },
      { title: "Data Scientist", company: "Mu Sigma", period: "2018 - 2020" },
    ],
    education: [
      { degree: "M.S. Data Science", institution: "IISc Bangalore", period: "2016 - 2018" },
    ],
  },
  {
    id: "24",
    name: "Sunita Mishra",
    title: "Technical Writer",
    location: "Pune, Maharashtra",
    email: "sunita@example.com",
    phone: "(+91) 90123-45679",
    description: "Creating clear and concise technical documentation for software products.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/24.jpg`,
    interests: ["Technical Writing", "API Documentation", "Information Architecture", "Reading"],
    experience: [
      { title: "Senior Technical Writer", company: "Oracle", period: "2018 - Present" },
      { title: "Technical Writer", company: "Tech Company", period: "2016 - 2018" },
    ],
    education: [
      { degree: "B.A. English", institution: "Pune University", period: "2012 - 2016" },
    ],
  },
  {
    id: "25",
    name: "Rajesh Kumar",
    title: "Sales Manager",
    location: "Mumbai, Maharashtra",
    email: "rajesh@example.com",
    phone: "(+91) 91234-56780",
    description: "Leading sales teams to achieve revenue targets in the B2B software space.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/25.jpg`,
    interests: ["Sales Strategy", "Team Leadership", "Negotiation", "Golf"],
    experience: [
      { title: "Regional Sales Manager", company: "Salesforce", period: "2017 - Present" },
      { title: "Account Executive", company: "SAP", period: "2014 - 2017" },
    ],
    education: [
      { degree: "MBA Marketing", institution: "NMIMS Mumbai", period: "2012 - 2014" },
    ],
  },
  {
    id: "26",
    name: "Kavita Patil",
    title: "Automation Tester",
    location: "Hyderabad, Telangana",
    email: "kavita@example.com",
    phone: "(+91) 92345-67891",
    description: "Developing and executing automated test scripts using Selenium and Java.",
    status: "Inactive",
    avatar: `https://randomuser.me/api/portraits/women/26.jpg`,
    interests: ["Test Automation", "Selenium", "Java", "Trekking"],
    experience: [
      { title: "Senior QA Automation Engineer", company: "Infosys", period: "2019 - Present" },
      { title: "QA Engineer", company: "Capgemini", period: "2016 - 2019" },
    ],
    education: [
      { degree: "B.Tech ECE", institution: "JNTU Hyderabad", period: "2012 - 2016" },
    ],
  },
  {
    id: "27",
    name: "Amit Singh",
    title: "iOS Developer",
    location: "Gurugram, Haryana",
    email: "amit@example.com",
    phone: "(+91) 93456-78902",
    description: "Building native iOS applications using Swift and Objective-C.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/27.jpg`,
    interests: ["iOS Development", "Swift", "Mobile Architecture", "Gaming"],
    experience: [
      { title: "iOS Developer", company: "Paytm", period: "2020 - Present" },
      { title: "Software Engineer (Mobile)", company: "Startup", period: "2018 - 2020" },
    ],
    education: [
      { degree: "B.E. IT", institution: "Thapar University", period: "2014 - 2018" },
    ],
  },
  {
    id: "28",
    name: "Shreya Gupta",
    title: "Digital Marketer",
    location: "Delhi",
    email: "shreya@example.com",
    phone: "(+91) 94567-89013",
    description: "Managing multi-channel digital marketing campaigns including PPC, Social Media, and Email.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/28.jpg`,
    interests: ["PPC", "Social Media Marketing", "Content Marketing", "Photography"],
    experience: [
      { title: "Digital Marketing Manager", company: "Advertising Agency", period: "2018 - Present" },
      { title: "Marketing Executive", company: "Retail Brand", period: "2016 - 2018" },
    ],
    education: [
      { degree: "BBA", institution: "Delhi University", period: "2012 - 2016" },
    ],
  },
  {
    id: "29",
    name: "Nikhil Sharma",
    title: "Security Analyst",
    location: "Bengaluru, Karnataka",
    email: "nikhil@example.com",
    phone: "(+91) 95678-90124",
    description: "Protecting information systems by identifying and mitigating security threats.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/29.jpg`,
    interests: ["Cyber Security", "Penetration Testing", "Network Security", "Ethical Hacking"],
    experience: [
      { title: "Security Analyst", company: "Cisco", period: "2019 - Present" },
      { title: "IT Security Specialist", company: "Consulting Firm", period: "2017 - 2019" },
    ],
    education: [
      { degree: "M.Tech Information Security", institution: "NIT Surathkal", period: "2015 - 2017" },
    ],
  },
  {
    id: "30",
    name: "Preeti Verma",
    title: "Recruiter",
    location: "Mumbai, Maharashtra",
    email: "preeti@example.com",
    phone: "(+91) 96789-01235",
    description: "Sourcing and hiring top talent for technical and non-technical roles.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/30.jpg`,
    interests: ["Recruitment", "Talent Sourcing", "HR Tech", "Reading Novels"],
    experience: [
      { title: "Technical Recruiter", company: "Google", period: "2020 - Present" },
      { title: "HR Associate", company: "Staffing Agency", period: "2018 - 2020" },
    ],
    education: [
      { degree: "Psychology", institution: "Mumbai University", period: "2014 - 2018" },
    ],
  },
  {
    id: "31",
    name: "Manish Kumar",
    title: "Systems Administrator",
    location: "Chennai, Tamil Nadu",
    email: "manish@example.com",
    phone: "(+91) 97890-12346",
    description: "Managing server infrastructure, operating systems, and network services.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/31.jpg`,
    interests: ["Linux Administration", "Windows Server", "Virtualization", "Movies"],
    experience: [
      { title: "Systems Administrator", company: "Accenture", period: "2015 - Present" },
      { title: "IT Support Engineer", company: "Local Company", period: "2013 - 2015" },
    ],
    education: [
      { degree: "Diploma in IT", institution: "Polytechnic", period: "2010 - 2013" },
    ],
  },
  {
    id: "32",
    name: "Swati Sharma",
    title: "Customer Success Manager",
    location: "Gurugram, Haryana",
    email: "swati@example.com",
    phone: "(+91) 98901-23457",
    description: "Ensuring customers achieve their desired outcomes while using the company's product.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/32.jpg`,
    interests: ["Customer Relationship Management", "SaaS", "Account Management", "Travel"],
    experience: [
      { title: "Customer Success Manager", company: "HubSpot", period: "2019 - Present" },
      { title: "Account Manager", company: "Software Company", period: "2017 - 2019" },
    ],
    education: [
      { degree: "Business Administration", institution: "MDI Gurgaon", period: "2015 - 2017" },
    ],
  },
  {
    id: "33",
    name: "Gaurav Singh",
    title: "AI Researcher",
    location: "Bengaluru, Karnataka",
    email: "gaurav@example.com",
    phone: "(+91) 99012-34568",
    description: "Conducting research in artificial intelligence, particularly in NLP and Computer Vision.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/33.jpg`,
    interests: ["Artificial Intelligence", "NLP", "Computer Vision", "Research Papers"],
    experience: [
      { title: "AI Researcher", company: "Research Lab", period: "2021 - Present" },
      { title: "Research Intern", company: "Tech Giant", period: "2020 - 2021" },
    ],
    education: [
      { degree: "Ph.D. Computer Science", institution: "IISc Bangalore", period: "Ongoing" },
    ],
  },
  {
    id: "34",
    name: "Aisha Khan",
    title: "Event Manager",
    location: "Delhi",
    email: "aisha@example.com",
    phone: "(+91) 90123-45679",
    description: "Planning and executing corporate events, conferences, and workshops.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/34.jpg`,
    interests: ["Event Planning", "Vendor Management", "Hospitality", "Music Festivals"],
    experience: [
      { title: "Event Manager", company: "Event Management Co.", period: "2017 - Present" },
      { title: "Event Coordinator", company: "Hotel Group", period: "2015 - 2017" },
    ],
    education: [
      { degree: "Hotel Management", institution: "IHM Pusa", period: "2011 - 2015" },
    ],
  },
  {
    id: "35",
    name: "Varun Mehta",
    title: "Investment Banker",
    location: "Mumbai, Maharashtra",
    email: "varun@example.com",
    phone: "(+91) 91234-56780",
    description: "Advising companies on mergers, acquisitions, and capital raising.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/35.jpg`,
    interests: ["Finance", "Mergers & Acquisitions", "Capital Markets", "Stock Trading"],
    experience: [
      { title: "Associate", company: "J.P. Morgan", period: "2018 - Present" },
      { title: "Analyst", company: "Goldman Sachs", period: "2016 - 2018" },
    ],
    education: [
      { degree: "MBA Finance", institution: "IIM Ahmedabad", period: "2014 - 2016" },
    ],
  },
  {
    id: "36",
    name: "Sakshi Agarwal",
    title: "Legal Counsel",
    location: "Gurugram, Haryana",
    email: "sakshi@example.com",
    phone: "(+91) 92345-67891",
    description: "Providing legal advice and support on corporate and commercial matters.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/36.jpg`,
    interests: ["Corporate Law", "Contract Negotiation", "Compliance", "Reading"],
    experience: [
      { title: "Legal Counsel", company: "Microsoft", period: "2019 - Present" },
      { title: "Lawyer", company: "Law Firm", period: "2016 - 2019" },
    ],
    education: [
      { degree: "LL.B", institution: "National Law School", period: "2011 - 2016" },
    ],
  },
  {
    id: "37",
    name: "Yash Gupta",
    title: "Game Developer",
    location: "Pune, Maharashtra",
    email: "yash@example.com",
    phone: "(+91) 93456-78902",
    description: "Developing games using Unity and C# for mobile and PC platforms.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/37.jpg`,
    interests: ["Game Development", "Unity", "C#", "Playing Games"],
    experience: [
      { title: "Game Developer", company: "Ubisoft", period: "2018 - Present" },
      { title: "Junior Developer", company: "Indie Game Studio", period: "2016 - 2018" },
    ],
    education: [
      { degree: "Game Design & Development", institution: "Gaming Institute", period: "2012 - 2016" },
    ],
  },
  {
    id: "38",
    name: "Nidhi Singh",
    title: "Biomedical Engineer",
    location: "Hyderabad, Telangana",
    email: "nidhi@example.com",
    phone: "(+91) 94567-89013",
    description: "Designing and developing medical devices and equipment.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/38.jpg`,
    interests: ["Medical Devices", "Biomaterials", "Healthcare Technology", "Volunteering"],
    experience: [
      { title: "Biomedical Engineer", company: "GE Healthcare", period: "2019 - Present" },
      { title: "Research Assistant", company: "University Lab", period: "2017 - 2019" },
    ],
    education: [
      { degree: "M.Tech Biomedical Engineering", institution: "IIT Madras", period: "2015 - 2017" },
    ],
  },
  {
    id: "39",
    name: "Tarun Khanna",
    title: "Supply Chain Manager",
    location: "Delhi",
    email: "tarun@example.com",
    phone: "(+91) 95678-90124",
    description: "Managing logistics, inventory, and supplier relationships.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/39.jpg`,
    interests: ["Supply Chain Management", "Logistics", "Procurement", "Cricket"],
    experience: [
      { title: "Supply Chain Manager", company: "Amazon", period: "2016 - Present" },
      { title: "Logistics Coordinator", company: "Flipkart", period: "2014 - 2016" },
    ],
    education: [
      { degree: "MBA Operations", institution: "SP Jain", period: "2012 - 2014" },
    ],
  },
  {
    id: "40",
    name: "Shilpa Reddy",
    title: "Architect",
    location: "Bengaluru, Karnataka",
    email: "shilpa@example.com",
    phone: "(+91) 96789-01235",
    description: "Designing residential and commercial buildings with a focus on sustainability.",
    status: "Inactive",
    avatar: `https://randomuser.me/api/portraits/women/40.jpg`,
    interests: ["Architecture", "Sustainable Design", "Urban Planning", "Sketching"],
    experience: [
      { title: "Senior Architect", company: "Architecture Firm", period: "2015 - Present" },
      { title: "Junior Architect", company: "Design Studio", period: "2012 - 2015" },
    ],
    education: [
      { degree: "B.Arch", institution: "SPA Delhi", period: "2007 - 2012" },
    ],
  },
  {
    id: "41",
    name: "Pranav Mishra",
    title: "Python Developer",
    location: "Pune, Maharashtra",
    email: "pranav@example.com",
    phone: "(+91) 97890-12346",
    description: "Developing backend applications and APIs using Python and Django/Flask.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/41.jpg`,
    interests: ["Python", "Django", "Flask", "Web Scraping", "Open Source"],
    experience: [
      { title: "Python Developer", company: "Software Company", period: "2019 - Present" },
      { title: "Backend Intern", company: "Startup", period: "2018 - 2019" },
    ],
    education: [
      { degree: "B.Tech IT", institution: "VIT Pune", period: "2015 - 2019" },
    ],
  },
  {
    id: "42",
    name: "Ritika Sharma",
    title: "Financial Analyst",
    location: "Mumbai, Maharashtra",
    email: "ritika@example.com",
    phone: "(+91) 98901-23457",
    description: "Analyzing financial data, creating forecasts, and supporting investment decisions.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/42.jpg`,
    interests: ["Financial Modeling", "Investment Analysis", "Excel", "Stock Market"],
    experience: [
      { title: "Financial Analyst", company: "Reliance Industries", period: "2020 - Present" },
      { title: "Finance Intern", company: "Bank", period: "2019 - 2020" },
    ],
    education: [
      { degree: "M.Com", institution: "Mumbai University", period: "2017 - 2019" },
    ],
  },
  {
    id: "43",
    name: "Vishal Nair",
    title: "Consultant",
    location: "Gurugram, Haryana",
    email: "vishal@example.com",
    phone: "(+91) 99012-34568",
    description: "Providing management consulting services to clients in various industries.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/43.jpg`,
    interests: ["Management Consulting", "Strategy", "Problem Solving", "Travel"],
    experience: [
      { title: "Consultant", company: "McKinsey & Company", period: "2018 - Present" },
      { title: "Business Analyst", company: "BCG", period: "2016 - 2018" },
    ],
    education: [
      { degree: "MBA", institution: "ISB Hyderabad", period: "2014 - 2016" },
    ],
  },
  {
    id: "44",
    name: "Garima Singh",
    title: "Interior Designer",
    location: "Delhi",
    email: "garima@example.com",
    phone: "(+91) 90123-45679",
    description: "Designing functional and aesthetically pleasing interior spaces.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/44.jpg`,
    interests: ["Interior Design", "Space Planning", "Furniture Design", "Art"],
    experience: [
      { title: "Interior Designer", company: "Design Firm", period: "2016 - Present" },
      { title: "Design Assistant", company: "Freelancer", period: "2014 - 2016" },
    ],
    education: [
      { degree: "Interior Design", institution: "NIFT Delhi", period: "2010 - 2014" },
    ],
  },
  {
    id: "45",
    name: "Sumit Patil",
    title: "Mechanical Engineer",
    location: "Chennai, Tamil Nadu",
    email: "sumit@example.com",
    phone: "(+91) 91234-56780",
    description: "Designing and analyzing mechanical systems and components.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/45.jpg`,
    interests: ["Mechanical Design", "CAD", "Thermodynamics", "Automobiles"],
    experience: [
      { title: "Mechanical Engineer", company: "Larsen & Toubro", period: "2017 - Present" },
      { title: "Trainee Engineer", company: "Manufacturing Co.", period: "2016 - 2017" },
    ],
    education: [
      { degree: "B.E. Mechanical", institution: "Anna University", period: "2012 - 2016" },
    ],
  },
  {
    id: "46",
    name: "Jyoti Kumari",
    title: "Teacher",
    location: "Patna, Bihar",
    email: "jyoti@example.com",
    phone: "(+91) 92345-67891",
    description: "Educating high school students in Mathematics and Science.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/46.jpg`,
    interests: ["Teaching", "Mathematics", "Science", "Mentoring"],
    experience: [
      { title: "High School Teacher", company: "Public School", period: "2015 - Present" },
      { title: "Assistant Teacher", company: "Private School", period: "2013 - 2015" },
    ],
    education: [
      { degree: "B.Ed", institution: "Patna University", period: "2012 - 2013" },
      { degree: "B.Sc Physics", institution: "Patna University", period: "2009 - 2012" },
    ],
  },
  {
    id: "47",
    name: "Alok Nath",
    title: "Civil Engineer",
    location: "Kolkata, West Bengal",
    email: "alok@example.com",
    phone: "(+91) 93456-78902",
    description: "Overseeing construction projects and infrastructure development.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/47.jpg`,
    interests: ["Structural Engineering", "Construction Management", "AutoCAD", "Bridge Design"],
    experience: [
      { title: "Senior Civil Engineer", company: "Construction Company", period: "2014 - Present" },
      { title: "Site Engineer", company: "Infrastructure Firm", period: "2011 - 2014" },
    ],
    education: [
      { degree: "B.E. Civil", institution: "Jadavpur University", period: "2007 - 2011" },
    ],
  },
  {
    id: "48",
    name: "Barkha Dutt", // Note: Using a famous name for variety, treat as fictional profile
    title: "Journalist",
    location: "Delhi",
    email: "barkha@example.com",
    phone: "(+91) 94567-89013",
    description: "Investigative journalist covering politics and social issues.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/48.jpg`,
    interests: ["Journalism", "Politics", "Investigative Reporting", "Writing"],
    experience: [
      { title: "Senior Editor", company: "Media House", period: "2010 - Present" },
      { title: "Reporter", company: "News Channel", period: "2005 - 2010" },
    ],
    education: [
      { degree: "Journalism", institution: "Columbia University", period: "2003 - 2005" }, // Example
    ],
  },
  {
    id: "49",
    name: "Chirag Jain",
    title: "Entrepreneur",
    location: "Bengaluru, Karnataka",
    email: "chirag@example.com",
    phone: "(+91) 95678-90124",
    description: "Founder of a tech startup focused on sustainable solutions.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/men/49.jpg`,
    interests: ["Startups", "Sustainability", "Innovation", "Networking"],
    experience: [
      { title: "Founder & CEO", company: "EcoTech Innovations", period: "2019 - Present" },
      { title: "Product Manager", company: "Established Tech Co", period: "2015 - 2019" },
    ],
    education: [
      { degree: "B.Tech + M.Tech", institution: "IIT Bombay", period: "2010 - 2015" },
    ],
  },
  {
    id: "50",
    name: "Dia Mirza", // Note: Using a famous name for variety, treat as fictional profile
    title: "Environmentalist",
    location: "Mumbai, Maharashtra",
    email: "dia@example.com",
    phone: "(+91) 96789-01235",
    description: "Advocate for environmental conservation and sustainable living.",
    status: "Active",
    avatar: `https://randomuser.me/api/portraits/women/50.jpg`,
    interests: ["Environment", "Conservation", "Activism", "Wildlife"],
    experience: [
      { title: "Goodwill Ambassador", company: "UN Environment Programme", period: "Ongoing" },
      { title: "Founder", company: "Conservation Initiative", period: "Various" },
    ],
    education: [
      { degree: "Social Work", institution: "University (Example)", period: "Various" },
    ],
  },
];

export default profiles; // Or export const profiles if using named exports